import './globals.css'
import { Poppins } from 'next/font/google'
import Providers from './Provider/Provider'
import "bootstrap/dist/css/bootstrap.css"

const inter = Poppins({
  weight: "400",
  display: "swap",
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`${inter.className}`}>

        <Providers>
          {children}
        </Providers>

      </body>
    </html>
  )
}
